"""
Cathepsin S cleavage site scoring for MHC-II antigen processing prediction.

Scores the likelihood that a given 15-mer peptide is generated by cathepsin S
digestion of the source protein in the endosomal compartment. Cathepsin S is
the dominant protease in the MHC-II antigen processing pathway in professional
antigen-presenting cells (dendritic cells, B cells).

The scoring uses a position-specific preference matrix derived from published
substrate profiling data (Choe et al. 2006 J Biol Chem; Biniossek et al. 2011
J Proteome Res; MEROPS database C01.034). The P2 position (S2 pocket) is the
strongest specificity determinant: Leu/Val strongly preferred, Asp/charged
residues essentially excluded.

No ML model. No training data. Literature-grounded amino acid lookup.
"""

from __future__ import annotations

import numpy as np


# ---------------------------------------------------------------------------
# Cathepsin S positional preference scores (log-odds vs uniform background)
# ---------------------------------------------------------------------------

# P2 — the dominant specificity determinant (S2 pocket)
# Choe et al. 2006: Leu (35%), Val (26%), Phe (9%), Ile (9%), Asp (0%)
_P2: dict[str, float] = {
    "L": 2.5, "V": 2.0, "F": 1.5, "I": 1.3, "M": 1.0, "W": 0.5,
    "Y": 0.3, "A": 0.2, "C": -0.3, "T": -0.5, "N": -0.5, "S": -0.5,
    "G": -1.0, "Q": -1.0, "P": -1.5, "H": -2.0, "R": -2.5, "K": -2.5,
    "E": -2.5, "D": -3.0,
}

# P1 — moderate selectivity (broadly tolerant except Pro)
_P1: dict[str, float] = {
    "G": 0.5, "K": 0.4, "T": 0.3, "Q": 0.3, "N": 0.3, "A": 0.2,
    "S": 0.2, "R": 0.2, "L": 0.1, "V": 0.1, "F": 0.0, "Y": 0.0,
    "H": 0.0, "I": 0.0, "M": 0.0, "E": -0.2, "D": -0.3, "W": -0.3,
    "C": -0.3, "P": -2.0,
}

# P1' — small/polar preferred after the cut
_P1P: dict[str, float] = {
    "A": 0.5, "S": 0.4, "E": 0.3, "G": 0.3, "N": 0.2, "T": 0.2,
    "V": 0.1, "L": 0.1, "I": 0.1, "Q": 0.1, "D": 0.0, "K": 0.0,
    "R": 0.0, "F": -0.1, "Y": -0.1, "H": -0.2, "M": -0.2, "C": -0.3,
    "W": -0.5, "P": -2.0,
}


def score_cleavage_site(antigen: str, position: int) -> float:
    """Score a single potential cathepsin S cleavage site.

    Parameters
    ----------
    antigen :
        Full protein sequence.
    position :
        0-based index of the cut (between position-1 and position).

    Returns
    -------
    Log-odds cleavage score.  Higher = more likely to be cut.
    P2 is weighted 3x because it is the dominant specificity determinant.
    """
    score = 0.0
    seq = antigen.upper()
    n = len(seq)

    # P2 (weighted 3x — dominant specificity)
    if position >= 2:
        score += _P2.get(seq[position - 2], 0.0) * 3.0
    # P1
    if position >= 1:
        score += _P1.get(seq[position - 1], 0.0)
    # P1'
    if position < n:
        score += _P1P.get(seq[position], 0.0)

    return score


def score_processing(
    peptide: str,
    antigen_sequence: str,
) -> float | None:
    """Score how likely a 15-mer is to be generated by cathepsin S processing.

    Finds the peptide's position in the antigen, scores both the
    N-terminal cleavage site (residues before the peptide start) and
    the C-terminal cleavage site (residues after the peptide end).
    Returns the sum of both site scores.

    Higher score = both boundaries are at favorable cathepsin S sites =
    the peptide is more likely to be naturally generated.

    Returns None if the peptide is not found in the antigen.
    """
    pos = antigen_sequence.upper().find(peptide.upper())
    if pos < 0:
        return None

    n_score = score_cleavage_site(antigen_sequence, pos)
    c_score = score_cleavage_site(antigen_sequence, pos + len(peptide))

    return n_score + c_score


def score_processing_normalized(
    peptide: str,
    antigen_sequence: str,
    all_scores: list[float] | None = None,
) -> float:
    """Normalized processing score in [0, 1].

    If *all_scores* is provided (pre-computed scores for all peptides),
    normalizes as a percentile.  Otherwise uses a fixed sigmoid mapping.
    """
    raw = score_processing(peptide, antigen_sequence)
    if raw is None:
        return 0.5  # neutral

    if all_scores is not None and len(all_scores) > 1:
        # Percentile normalization
        idx = np.searchsorted(sorted(all_scores), raw, side="right")
        return idx / len(all_scores)

    # Fallback: sigmoid-like normalization centered at 0
    return 1.0 / (1.0 + np.exp(-raw * 0.3))
